[package]
name = "satjointsolver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.42", features = ["derive"]}
mimalloc = "0.1"
itertools = "0.12"
cadical = "0.1"
rayon = "1.8"
graph6 = "2.0.1"
